name: "depoloy to aws"
on: workflow_dispatch

jobs:
    deploy:
        runs-on: self-hosted
        
        steps:
            - name: "Set up nodejs"
              uses: actions/setupnode@v4
              with:
                  node-version: "20"
            - name: "Checkout code"
              uses: actions/checkout@v2

            - name: "Install depemdencies"
              run: npm install

            - name: "Install pm2 globally"
              run: npm install pm2 -g

            



